import turtle
turtle.Screen().bgcolor("green")
s=turtle.Screen()
s.setup(500,500)
turtle.title("new turtle draw website")
bd=turtle.Turtle()
bd.forward(100)
bd.left(90)
bd.forward(100)
bd.left(90)
bd.forward(100)
bd.left(90)
bd.forward(100)
bd.left(90)
turtle.done()